export default {
  CHANGE_LOGIN: 'user/CHANGE_LOGIN',
  CHANGE_USER: 'user/CHANGE_USER',
  CHANGE_USER_RECORD: 'user/CHANGE_USER_RECORD',
  CHANGE_USER_COLLECT: 'user/CHANGE_USER_COLLECT',
  CHANGE_LOADING: 'user/CHANGE_LOADING',
  CHANGE_STATE: 'user/CHANGE_STATE',
}
