export default {
  CHANGE_RECOMMEND: 'find/CHANGE_RECOMMEND',
  CHANGE_BANNER: 'find/CHANGE_BANNER',
  CHANGE_LOADING: 'find/CHANGE_LOADING',
  CHANGE_RECOMMEND_SONGS: 'find/CHANGE_RECOMMEND_SONGS',
  CHANGE_DailyRecommendation: 'find/CHANGE_DailyRecommendation',
}
